jwt:
  header: Authorization
  secret: my-very-secret-key
logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lulanches?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  resources:
    chain:
      enabled: true
  
management:
  security:
    enabled: false # set to false to disable 'default' Spring Boot security


