INSERT INTO ROLE(ID, ROLE) VALUES (1,'ROLE_ADMIN');
INSERT INTO ROLE(ID, ROLE) VALUES (2,'ROLE_USER_TESTE');


INSERT INTO USER_SNACKS (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVE, LAST_PASSWORD_RESET_DATE) VALUES (1, 'admin', '$2a$10$1cn9NZRKHOjY2W5ZHdM4iusgYeeTq8tf8vVAfHxvk2rolXeMSGtwe', 'admin', 'admin', 'admin@lulanches.com', 1, '2016-01-01');
INSERT INTO USER_SNACKS (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ACTIVE, LAST_PASSWORD_RESET_DATE) VALUES (2, 'user', '$2a$10$1cn9NZRKHOjY2W5ZHdM4iusgYeeTq8tf8vVAfHxvk2rolXeMSGtwe', 'user', 'user', 'user@lulanches.com', 1, '2016-01-01');

INSERT INTO USER_HAS_ROLE(USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USER_HAS_ROLE(USER_ID, ROLE_ID) VALUES (2,2);

INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR) VALUES (1,'Bread','Pão');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR) VALUES (2,'Cheese','Queijo');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR) VALUES (3,'Salad','Salada');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR) VALUES (4,'Sauce','Molho');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR) VALUES (5,'Spice','Tempero');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR) VALUES (6,'Filling','Recheio');

INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR)  VALUES (7,'Arugula','Rucula');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR)  VALUES (8,'Lettuce','Alface');
INSERT INTO DESCRIPTION_ITEM (ID, WORD_EN_US, WORD_PT_BR)  VALUES (9,'Tomato','Tomate');

INSERT INTO INGRIDIENT_TYPE (ID, TYPE_ID) VALUES (1, 3);
INSERT INTO INGRIDIENT (ID, PRICE,DESCRIPTION_ID, INGRIDIENT_TYPE_ID) VALUES (1, 0.99, 8, 1);